global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'mattermost-bridge'

receivers:
- name: 'mattermost-bridge'
  webhook_configs:
  - url: 'http://138.68.249.92:9094/alert'
    send_resolved: true

templates:
- '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']